//
// Created by nico on 23.07.19.
//

#ifndef EMPTY_ROSNODE_CPLUSPLUS_INCLUDE_EMPTY_ROSNODE_CPLUSPLUS_SOME_DUMMY_CLASS_H_
#define EMPTY_ROSNODE_CPLUSPLUS_INCLUDE_EMPTY_ROSNODE_CPLUSPLUS_SOME_DUMMY_CLASS_H_

class some_dummy_class {

};

#endif //EMPTY_ROSNODE_CPLUSPLUS_INCLUDE_EMPTY_ROSNODE_CPLUSPLUS_SOME_DUMMY_CLASS_H_
